name: repaint

description: >
  Custom paint alternative for Flutter, with more features.

version: 0.0.1

homepage: https://github.com/PlugFox/repaint

repository: https://github.com/PlugFox/repaint

issue_tracker: https://github.com/PlugFox/repaint/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - paint
  - painter
  - game
  - shader
  - custom

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library.'
#    path: example.png

environment:
  sdk: ^3.5.0
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  # Annotations
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  fake_async: ^1.3.0
  flutter_lints: '>=4.0.0 <6.0.0'

flutter:
